In [1]:
import word2vec
word2vec.word2phrase('processed_corpus.txt', 'processed_corpus.txt_phrases.txt', verbose=True)

Starting training using file processed_corpus.txt

Vocab size (unigrams + bigrams): 32209
Words in train file: 77897


In [2]:
# Actually train the model
word2vec.word2vec('processed_corpus.txt_phrases.txt', 'processed_corpus.txt_phrases.bin', size=200, verbose=True)

Starting training using file processed_corpus.txt_phrases.txt
Vocab size: 2449
Words in train file: 147087
Alpha: 0.000682  Progress: 99.52%  Words/thread/sec: 985.49k  61%  Words/thread/sec: 901.02k  

# 

In [3]:
# Make word clusters
word2vec.word2clusters('processed_corpus.txt_phrases.txt', 'processed_corpus.txt_phrases_cluster.txt', 200, verbose=True)

Starting training using file processed_corpus.txt_phrases.txt
Vocab size: 2449
Words in train file: 147087
Alpha: 0.000615  Progress: 98.90%  Words/thread/sec: 985.11k  pha: 0.006746  Progress: 75.60%  Words/thread/sec: 952.33k  

In [6]:
model = word2vec.load('processed_corpus.txt_phrases.bin')
model.vocab # the numpy array

array(['</s>', '沖繩', '人', ..., '紀念品店', '會給', '古代'], dtype='<U78')

In [7]:
model['沖繩'][:10]

array([-0.10678505, -0.0785195 ,  0.0839477 ,  0.02421554, -0.05690597,
       -0.0383428 ,  0.06008865, -0.08508331, -0.05571522,  0.11402877])

In [8]:
model.distance("沖繩", "潛水", "拉麵", "樂桃")

[('沖繩', '潛水', -0.057864482332644976),
 ('沖繩', '拉麵', 0.08893714307194141),
 ('沖繩', '樂桃', -0.08475903932545055),
 ('潛水', '拉麵', -0.059901027756377685),
 ('潛水', '樂桃', 0.05949208370481732),
 ('拉麵', '樂桃', 0.049583872268674)]

In [10]:
# Check what words are similar with the given query
indexes, metrics = model.similar("沖繩")
indexes, metrics

(array([ 486, 1639,  746, 1970,   65, 2314,  985, 2155, 1387, 1234]),
 array([0.23940034, 0.20631132, 0.20313511, 0.19391768, 0.1917904 ,
        0.19169094, 0.18655472, 0.18293922, 0.18259591, 0.18168525]))

In [11]:
model.vocab[indexes]

array(['珊瑚礁', '為主', 'カ', '樓下', '停車場', '水質', '旭橋', '大街', '菓子', '旺季'],
      dtype='<U78')